unclassified:
  gitHubPluginConfig:
    hookSecretConfigs:
      - credentialsId: github-webhook-shared-secret
    configs:
      - credentialsId: github-coreosbot-releng-token-text
        manageHooks: true
