unclassified:
  jmsProviders:
    configs:
      - rabbitMq:
          name: "Fedora Messaging"
          hostname: "rabbitmq.fedoraproject.org"
          portNumber: 5671
          virtualHost: "/public_pubsub"
          exchange: "amq.topic"
          authenticationMethod:
            x509Certificate:
              credentialId: "fedora-messaging-coreos-x509-cert"
